steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/synthos/frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://synthos-api-gateway-cdxwgptjqq-uc.a.run.app/api/v1'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/synthos/frontend:latest'
options:
  machineType: 'E2_HIGHCPU_8'
timeout: '1200s'
